spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/chatservice
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

logging:
  level:
    com.demoWebsocket : debug
    com.demoWebsocket.web.mapper: debug  # 마이바티스 쿼리 로그

mybatis:
  mapper-locations: classpath:mapper/**/*.xml