spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/mystudy
    username: root
    password: 1234

logging:
  level:
    com.demoCache : debug
    com.demoCache.web.mapper: debug  # 마이바티스 쿼리 로그
    
mybatis:
  mapper-locations:
  - classpath:mapper/*.xml
